import 'dart:convert';
import 'dart:core';
/*
import 'package:lphms_storage_plugin/function/uuid_generator.dart';
import 'package:lphms_storage_plugin/models/LHMS.dart';
import 'package:lphms_storage_plugin/utility/position_enum.dart';
import 'package:lphms_storage_plugin/utility/prov_enum.dart';
import 'package:lphms_storage_plugin/utility/record_prefix.dart';
*/
import '../../../models/LHMS.dart';
import '../../../utility/prov_enum.dart';
import '../../../utility/record_prefix.dart';
import '../../utility/uuid_generator.dart';

class HotelInfo {
  String? pk; //HO +
  String? sk; //register uuid ==> change to hotel activated status, HA_<True/False>
  String? hna;  //hotel name in lao
  @Deprecated("use in HotelRegInfo")
  String? gsi1; //secret password
  String? prov;  //province
  String? dis; //district
  String? mph;   //mobile for receiving register sms
  double? lat;   //latitude
  double? lon;   //longitude
  String? addr;
  List<String?>? hnl;
  HotelInfo({
    required this.pk,required this.sk,this.hna,@Deprecated("use in HotelRegInfo")this.gsi1,this.prov,this.dis,this.mph,this.lat,this.lon,this.addr,this.hnl});

  //Generate hotel for registration.
  // To generate hotel for registration, we need to create tow record.
  // One of it include these information: hotelId(pk),password(gsi1),
  // registration code uuid(sk),hotelName(hna),province(prov),district(dis),mobile(mph),
  // latitude(lat),longitude(lon),address(addr).
  // The other one include hotelId(pk),hotelName(in laos, as sk), which
  // used for hotel name search.
  // HotelId code like "HO_<district code>_<UUID>", district code like "RG_<district code>",
  // hotelName in laos code like "HN_<lang>_<hotel name>", uuid is generated by timestamp and random number,and code like "RI_<uuid>".
  // Password is generated by random number.
  //To register, customers provide uuid(sk) and password(gsi1) to get hotel id,
  //and other information of hotel, and use these information to finish hotel registration.
  //For customers to query register information. They can list(aws api query) hotels by hotelId begins "HO_<district code>" and sk begins with "RI_",
  // To query hotel information by hotelName, they can list(aws api query) hotels by hotelId begins "HO_<district code>" and sk begins with "HN_<lang>_<hotel name>".
  HotelInfo.createForReg({
    String? hotelName, String? province, String? district,
    String? mobile, double? latitude,double? longitude, String? address}){
    hna = hotelName;
    prov = province;
    dis = district;
    mph = mobile;
    lon = longitude;
    lat = latitude;
    addr = address;

    pk = _genHotelId();
    //sk = _genRegisterId();
    sk = "${rPref[RecType.hotelActivated]}${sp}FALSE";
    //gsi1 = generatePassword();

  }

  changeHotelId(){
    //replace hotel id district code with new district code
    pk = pk!.replaceFirst(RegExp(r"HO_[0-9]{2}_"), "HO$sp$dis$sp");
  }

  @Deprecated("use in HotelRegInfo")
  genRegisterId(){
    //if district code is null, generate hotel id with default district code
    //the default district code the first pk value of disLao(file lib/utility/prov_enum.dart)
    dis ??= disLao[0]['pk'];
    return "${rPref[RecType.register]}$sp${generateUuid()}";
  }

  HotelInfo.createFromReg(LHMS info){
    pk = info.PK;
    sk = info.SK;
    hna = info.hna;
    prov = info.prov;
    dis = info.dis;
    mph = info.mph;
    lat = info.lat;
    lon = info.lon;
    addr = info.addr;
    hnl = info.hnl;
  }
  HotelInfo.fromLHMS(LHMS info){
    pk = info.PK;
    sk = info.SK;
    hna = info.hna;
    prov = info.prov;
    dis = info.dis;
    mph = info.mph;
    lat = info.lat;
    lon = info.lon;
    addr = info.addr;
    hnl = info.hnl;
  }
  HotelInfo.fromJson(json){
    print("HotelInfo.fromJson: $json,${json.runtimeType}");
    pk = json['PK'] ;
    sk = json['SK'] ;
    hna = json['hna'] as String?;
    prov = json['prov'] as String?;
    dis = json['dis'] as String?;
    mph = json['mph'] as String?;
    lat = json['lat'] as double?;
    lon = json['lon'] as double?;
    addr = json['addr'] as String?;
    hnl = List<String?>.from(json['hnl']);
  }
  String _genHotelId() {
    //if district code is null, generate hotel id with default district code
    //the default district code the first pk value of disLao(file lib/utility/prov_enum.dart)
    dis ??= disLao[0]['pk'];
    return "${rPref[RecType.hotel]}$sp$dis$sp${generateHotelId()}";
  }
  Map<String,dynamic> toJson() =>
     {
      'pk':pk,
      'sk':sk,
      'hna':hna,
      'prov':prov,
      'dis':dis,
      'mph':mph,
      'lat':lat,
      'lon':lon,
      'addr':addr,
       'hnl':jsonEncode(hnl),
    };

  toJsonString() => jsonEncode(toJson());

      //'{"pk":"$pk","sk":"$sk","hna":"$hna","prov":"$prov","dis":"$dis","mph":"$mph","lat":$lat,"lon":$lon,"addr":"$addr"}';

  LHMS toLHMS(){
    return LHMS(PK: pk!,SK: sk!,hna: hna, prov: prov, dis: dis, mph: mph, lat: lat, lon: lon, addr: addr,hnl: hnl);
  }

}

class HotelName {
  late String pk; //hotel Id
  late String sk; //HN_<lang>_<hotel name>

  static genHotelName(String hotelName,String lang) => "${rPref[RecType.hotelName]}$sp$lang$sp$hotelName";

  HotelName({required this.pk, required this.sk});

  HotelName.create({required String hotelId,required String hotelName,required String lang}){
    pk = hotelId;
    sk = genHotelName(hotelName, lang);
  }
  HotelName.fromLHMS(LHMS info){
    pk = info.PK;
    sk = info.SK;
  }

  LHMS toLHMS(){
    return LHMS(PK: pk, SK: sk,);
  }
}
//hotel activated or not. only one record for each hotel.
@Deprecated("set hotelInfo sk as 'HA_<True/False>'")
class HotelActivated {
  String? pk; //hotel Id
  String? sk; //HA_<TRUE/FALSE>
  HotelActivated({required this.pk, required this.sk});

  HotelActivated.fromLHMS(LHMS info){
    pk = info.PK;
    sk = info.SK;
  }

  LHMS toLHMS(){
    return LHMS(PK: pk!, SK: sk!);
  }
}

class HotelRegInfo{
  String? pk; //hotel Id
  String? sk; //register uuid, like: RI_<uuid>
  String? gsi1;  //register password, 4 characters

  HotelRegInfo({required this.pk, required this.sk, required this.gsi1});

  HotelRegInfo.create({required String hotelId}){
    pk = hotelId;
    sk = _genRegisterId;
    gsi1 = _genPassword;
  }
  get _genRegisterId => "${rPref[RecType.register]}$sp${generateUuid()}";
  get _genPassword => generatePassword();

  HotelRegInfo.fromLHMS(LHMS info){
    pk = info.PK;
    sk = info.SK;
    gsi1 = info.GSI1;
  }

  LHMS toLHMS(){
    return LHMS(PK: pk!, SK: sk!, GSI1: gsi1!);
  }
}
